path:
  data_dir: datasets
  feat_dir: feats

train:
  autoencoder_learning_rate: 0.001

  # for LSTM classifier
  lstm_train_epoch_num: 10000
  lstm_learning_rate: 0.001
  lstm_batch_size: 50
  lstm_valid_interval: 1000


model:
  embed_dims: 512

  # for LSTM classifier
  lstm_neuron_num: 128


audio:
  sampling_rate: 16000
  n_fft: 1024
  time_length: 90
  hop_length: 256
  win_length: 400
  min_level_db: -100.0
  ref_level_db: 20.0
  fmin: 125
  fmax: 7600
  n_mels: 80
