path:
  data_dir: datasets
  feat_dir: feats
  #feat_dir: feats_mel

autoencoder:
  initial_learning_rate: 0.001  # MSE
  end_learning_rate: 0.00001    # MSE
  #initial_learning_rate: 0.00001  # CCE
  #end_learning_rate: 0.0000001    # CCE
  lr_decay_rate: 0.96
  train_epoch_num: 10000
  embed_dims: 256
  valid_interval: 1000
  chkpt_interval: 1000
  batch_size: 6  # number of data participating in actual training : batch_size * (number of keyword)

bagan:
  initial_learning_rate: 0.001
    end_learning_rate: 0.00001
    lr_decay_rate: 0.96
    train_epoch_num: 10000
    embed_dims: 256
    valid_interval: 1000
    chkpt_interval: 1000
    batch_size: 6  # number of data participating in actual training : batch_size * (number of keyword)

classifier:
  train_epoch_num: 10000
  initial_learning_rate: 0.00001
  end_learning_rate: 0.000001
  lr_decay_rate: 0.96
  batch_size: 6  # number of data participating in actual training : batch_size * (number of keyword + 1)
  valid_interval: 1000
  chkpt_interval: 1000


audio:
  sampling_rate: 16000
  rescaling_max: 0.999
  n_fft: 1024
  time_length: 101
  hop_length: 160
  win_length: 480
  min_level_db: -100.0
  ref_level_db: 20.0
  fmin: 125
  fmax: 7600
  n_mels: 80
  n_mfcc: 40
