path:
  data_dir: datasets
  feat_dir: feats

train:
  autoencoder_learning_rate: 0.001

  # for LSTM classifier.py
  lstm_train_epoch_num: 10000
  lstm_learning_rate: 0.00001
  lstm_batch_size: 6  # number of data participating in actual training : batch_size * 11
  lstm_valid_interval: 1000
  lstm_chkpt_interval: 5000

model:
  embed_dims: 512

  # for LSTM classifier.py
  lstm_neuron_num: 256


audio:
  sampling_rate: 16000
  rescaling_max: 0.999
  n_fft: 1024
  time_length: 63
  hop_length: 256
  win_length: 400
  min_level_db: -100.0
  ref_level_db: 20.0
  fmin: 125
  fmax: 7600
  n_mels: 80
