path:
  data_dir: datasets
  feat_dir: feats

train:
  autoencoder_learning_rate: 0.001

model:
  embed_dims: 512

audio:
  sampling_rate: 16000
  n_fft: 1024
  time_length: 90
  hop_length: 256
  win_length: 400
  min_level_db: -100.0
  ref_level_db: 20.0
  fmin: 125
  fmax: 7600
  n_mels: 80
